"""Merge sheets from the Bakken 2018 Excel Well Workbook."""

from __future__ import annotations

import pandas as pd

# Core header + formation columns (first merge stage)
HEADER_FORMATION_COLUMNS: list[str] = [
    "UWI",
    "Operator Name",
    "Current Operator Name",
    "Lease Name",
    "Well Num",
    "OS Indicator",
    "Hole Direction",
    "Final Status",
    "Current Status",
    "Basin",
    "Basin Code",
    "Sub Basin",
    "Sub Basin Code",
    "Play Name",
    "Play Type",
    "Permit Date",
    "Depth Total Driller",
    "Depth Total Logger",
    "Depth True Vertical",
    "Depth Whipstock",
    "Class Initial Name",
    "Class Initial Code",
    "Class Final Name",
    "Class Final Code",
    "Status Final Code",
    "Formation Projected Name",
    "Depth Total Projected",
    "Formation at TD Name",
    "PRODFit Formation at TD Name",
    "Formation Producing Name",
    "PRODFit Top Formation Producing Name",
    "PRODFit Base Formation Producing Name",
    "Elevation Reference Value",
    "Elevation Reference Datum",
    "Ground Elevation",
    "Date First Spud",
    "Date Spud",
    "Date Completion",
    "Date Rig Release",
    "Date First Report",
    "Date Last Activity",
    "Depth Water Value",
    "Depth Water Datum",
    "Surface Latitude",
    "Surface Longitude",
    "Surface LL Source",
    "BH Latitude",
    "BH Longitude",
    "BH LL Source",
    "Activity Code",
    "Source_y",
    "Num Frac Stages",
    "Stages Avail",
    "Num Treatment Records",
    "Proppant - Sand (lbs)",
    "Proppant - Resin Coated Sand (lbs)",
    "Proppant - Ceramic (lbs)",
    "Proppant - Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Sand (lbs)",
    "Proppant - Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Sand, Resin Coated Sand, Ceramic, Resin Coated Ceramic (lbs)",
    "Proppant - Bauxite (lbs)",
    "Proppant - Walnut (lbs)",
    "Proppant - Marble (lbs)",
    "Proppant - Gravel (lbs)",
    "Proppant - Sand, Bauxite Ceramic (lbs)",
    "Proppant - Other (lbs)",
    "Total Proppant (lbs)",
    "Fluid/Water (Gals)",
    "Fluid - Slick Water (Gals)",
    "Fluid - Salt Water (Gals)",
    "Fluid - Foam (Gals)",
    "Fluid - Oil (Gals)",
    "Fluid - Potassium Chloride (Gals)",
    "Fluid - Surfactant (Gals)",
    "Fluid - Emulsion (Gals)",
    "N2/CO2 Gas (Gals)",
    "Acid (Gals)",
    "Gel/x-link (Gals)",
    "Fluid - Explosive (Gals)",
    "Fluid - Other (Gals)",
    "Total Fluid (gals)",
    "Total Proppant (lbs.) / Total Fluid (gal)",
    "Top Source",
    "Interpreter",
    "Code",
    "Name",
    "Depth Top",
    "Depth Top UOM",
    "Base Depth",
    "Base Depth UOM",
]

# Columns after joining Completion sheet
FULL_WORKBOOK_COLUMNS: list[str] = HEADER_FORMATION_COLUMNS + [
    "Depth Top_x",
    "Depth Top UOM_x",
    "Source_x",
    "Test Type",
    "Pressure Obs Number",
    "Fluid Type",
    "BH Pressure Obs Number",
    "Date",
    "Formation Top Name_x",
    "Formation Base Name_x",
    "Depth Top_y",
    "Depth Base_x",
    "PRODFit Top Formation",
    "PRODFit Base Formation",
    "Pressure Flowing Tubing",
    "Pressure Flowing Casing",
    "Pressure Shutin Tubing",
    "Pressure Shutin Casing",
    "Bottom Hole Run Depth",
    "Pressure Bottom Hole",
    "Number",
    "Formation Top Name_y",
    "Formation Base Name_y",
    "Depth Top",
    "Depth Top UOM_y",
    "Depth Base_y",
    "Depth Base UOM",
    "Type",
    "Method",
]


def build_merged_workbook(workbook: pd.ExcelFile) -> pd.DataFrame:
    """Merge header, formation, and completion sheets on ``UWI``."""
    header = workbook.parse(0)
    formation = workbook.parse("Formation")
    completion = workbook.parse("Completion")

    merged = header.merge(formation, on="UWI", how="outer")
    header_cols = [c for c in HEADER_FORMATION_COLUMNS if c in merged.columns]
    merged = merged[header_cols]
    merged = merged.merge(completion, on="UWI", how="outer")

    available = [col for col in FULL_WORKBOOK_COLUMNS if col in merged.columns]
    return merged[available]
